import Foundation

enum ReadingContentService {
    static func textForToday(profile: ChildProfile, date: String) -> ReadingText {
        let texts = allTexts.filter { $0.ageGroup == profile.ageGroup }
        guard !texts.isEmpty else { return allTexts[0] }
        let hash = abs(date.hashValue)
        return texts[hash % texts.count]
    }

    static func parseWords(from text: String) -> [ReadingWord] {
        let components = text.components(separatedBy: " ").filter { !$0.isEmpty }
        var words: [ReadingWord] = []
        var charIndex = 0
        for (i, word) in components.enumerated() {
            let start = charIndex
            let end = charIndex + word.count
            words.append(ReadingWord(id: i, text: word, startIndex: start, endIndex: end))
            charIndex = end + 1
        }
        return words
    }

    static func secondsPerWord(totalWords: Int, targetSeconds: Int) -> Double {
        guard totalWords > 0 else { return 1.0 }
        return Double(targetSeconds) / Double(totalWords)
    }

    private static let allTexts: [ReadingText] = youngTextsEN + middleTextsEN + olderTextsEN

    private static let youngTextsEN: [ReadingText] = [
        ReadingText(
            id: "y1", titleEN: "The Little Cat", titleNO: "Den lille katten",
            titleES: "La gatita", titlePT: "A gatinha",
            contentEN: "The sun is up. A small cat sits on a red mat. The cat is soft and warm. It has big green eyes. The cat likes to nap in the sun. It purrs and purrs. A yellow bird sings in a tall tree. The cat looks up at the bird. The bird flies far away. The cat yawns and goes back to sleep. What a lazy day!",
            contentNO: "Solen er oppe. En liten katt sitter p\u{00E5} en r\u{00F8}d matte. Katten er myk og varm. Den har store gr\u{00F8}nne \u{00F8}yne. Katten liker \u{00E5} sove i solen. Den spinner og spinner. En gul fugl synger i et h\u{00F8}yt tre. Katten ser opp p\u{00E5} fuglen. Fuglen flyr langt bort. Katten gjesper og sover videre. For en lat dag!",
            contentES: "Ha salido el sol. Una gatita peque\u{00F1}a est\u{00E1} sentada sobre una alfombra roja. La gatita es suave y calentita. Tiene unos ojos verdes muy grandes. Le gusta echarse una siesta al sol. Ronronea y ronronea. Un p\u{00E1}jaro amarillo canta en un \u{00E1}rbol alto. La gatita mira al p\u{00E1}jaro. El p\u{00E1}jaro se aleja volando. La gatita bosteza y vuelve a dormirse. \u{00A1}Qu\u{00E9} d\u{00ED}a tan tranquilo!",
            contentPT: "O sol j\u{00E1} nasceu. Uma gatinha pequena est\u{00E1} sentada num tapete vermelho. A gatinha \u{00E9} macia e quentinha. Tem uns olhos verdes muito grandes. Gosta de dormir uma sesta ao sol. Ronrona sem parar. Um p\u{00E1}ssaro amarelo canta numa \u{00E1}rvore alta. A gatinha olha para o p\u{00E1}ssaro. O p\u{00E1}ssaro voa para longe. A gatinha boceja e volta a dormir. Que dia t\u{00E3}o pregui\u{00E7}oso!",
            ageGroup: .young
        ),
        ReadingText(
            id: "y2", titleEN: "My Dog Sam", titleNO: "Hunden min Sam",
            titleES: "Mi perro Sam", titlePT: "O meu c\u{00E3}o Sam",
            contentEN: "I have a dog. His name is Sam. Sam is brown and big. He likes to run in the park. He can catch a ball! Sam wags his tail when he is happy. He loves to play with me. We run and jump all day. Then we sit and rest. Sam puts his head on my lap. He is my best friend.",
            contentNO: "Jeg har en hund. Han heter Sam. Sam er brun og stor. Han liker \u{00E5} l\u{00F8}pe i parken. Han kan fange en ball! Sam logrer med halen n\u{00E5}r han er glad. Han elsker \u{00E5} leke med meg. Vi l\u{00F8}per og hopper hele dagen. S\u{00E5} sitter vi og hviler. Sam legger hodet sitt i fanget mitt. Han er min beste venn.",
            contentES: "Tengo un perro. Se llama Sam. Sam es marr\u{00F3}n y grande. Le gusta correr por el parque. \u{00A1}Puede atrapar una pelota! Sam mueve la cola cuando est\u{00E1} contento. Le encanta jugar conmigo. Corremos y saltamos todo el d\u{00ED}a. Luego nos sentamos a descansar. Sam apoya la cabeza en mi regazo. Es mi mejor amigo.",
            contentPT: "Tenho um c\u{00E3}o. Chama-se Sam. O Sam \u{00E9} castanho e grande. Gosta de correr no parque. Consegue apanhar uma bola! O Sam abana a cauda quando est\u{00E1} feliz. Adora brincar comigo. Corremos e saltamos o dia todo. Depois sentamo-nos a descansar. O Sam pousa a cabe\u{00E7}a no meu colo. \u{00C9} o meu melhor amigo.",
            ageGroup: .young
        ),
        ReadingText(
            id: "y3", titleEN: "The Rain", titleNO: "Regnet",
            titleES: "La lluvia", titlePT: "A chuva",
            contentEN: "Drop, drop, drop! It is raining today. I look out the window. The sky is gray. I see big puddles on the ground. I put on my yellow coat. I put on my red boots. I go out to play! I jump in the puddles. Splash, splash! The rain feels cool on my face. I love rainy days. When I come home, I drink warm milk.",
            contentNO: "Drypp, drypp, drypp! Det regner i dag. Jeg ser ut av vinduet. Himmelen er gr\u{00E5}. Jeg ser store pytter p\u{00E5} bakken. Jeg tar p\u{00E5} meg den gule jakken. Jeg tar p\u{00E5} meg de r\u{00F8}de st\u{00F8}vlene. Jeg g\u{00E5}r ut for \u{00E5} leke! Jeg hopper i pyttene. Plask, plask! Regnet f\u{00F8}les kaldt p\u{00E5} ansiktet mitt. Jeg elsker regnv\u{00E6}rsdager.",
            contentES: "\u{00A1}Plin, plin, plin! Hoy est\u{00E1} lloviendo. Miro por la ventana. El cielo est\u{00E1} gris. Veo charcos grandes en el suelo. Me pongo mi abrigo amarillo. Me pongo mis botas rojas. \u{00A1}Salgo a jugar! Salto en los charcos. \u{00A1}Chap, chap! La lluvia se siente fresquita en mi cara. Me encantan los d\u{00ED}as de lluvia. Cuando vuelvo a casa, bebo leche calentita.",
            contentPT: "Plic, plic, plic! Hoje est\u{00E1} a chover. Olho pela janela. O c\u{00E9}u est\u{00E1} cinzento. Vejo po\u{00E7}as grandes no ch\u{00E3}o. Visto o meu casaco amarelo. Cal\u{00E7}o as minhas botas vermelhas. Vou brincar para a rua! Salto nas po\u{00E7}as. Chap, chap! A chuva sabe t\u{00E3}o fresca na minha cara. Adoro dias de chuva. Quando chego a casa, bebo leite morno.",
            ageGroup: .young
        ),
        ReadingText(
            id: "y4", titleEN: "The Big Tree", titleNO: "Det store treet",
            titleES: "El gran \u{00E1}rbol", titlePT: "A grande \u{00E1}rvore",
            contentEN: "In my garden there is a big tree. It has many green leaves. In spring, pink flowers grow on it. Birds make nests in the tree. I can hear them sing every morning. I like to sit under the tree. It gives me cool shade when it is hot. My dad says the tree is very old. I want to climb it one day!",
            contentNO: "I hagen min st\u{00E5}r et stort tre. Det har mange gr\u{00F8}nne blader. Om v\u{00E5}ren vokser rosa blomster p\u{00E5} det. Fugler lager reir i treet. Jeg kan h\u{00F8}re dem synge hver morgen. Jeg liker \u{00E5} sitte under treet. Det gir meg kjølig skygge n\u{00E5}r det er varmt. Pappa sier treet er veldig gammelt. Jeg vil klatre i det en dag!",
            contentES: "En mi jard\u{00ED}n hay un \u{00E1}rbol muy grande. Tiene muchas hojas verdes. En primavera le salen flores rosas. Los p\u{00E1}jaros hacen nidos en el \u{00E1}rbol. Puedo o\u{00ED}rlos cantar cada ma\u{00F1}ana. Me gusta sentarme debajo del \u{00E1}rbol. Me da una sombra fresca cuando hace calor. Mi padre dice que el \u{00E1}rbol es muy viejo. \u{00A1}Quiero subir a \u{00E9}l alg\u{00FA}n d\u{00ED}a!",
            contentPT: "No meu jardim h\u{00E1} uma \u{00E1}rvore muito grande. Tem muitas folhas verdes. Na primavera nascem nela flores cor-de-rosa. Os p\u{00E1}ssaros fazem ninhos na \u{00E1}rvore. Consigo ouvi-los cantar todas as manh\u{00E3}s. Gosto de me sentar debaixo da \u{00E1}rvore. D\u{00E1}-me sombra fresca quando est\u{00E1} calor. O meu pai diz que a \u{00E1}rvore \u{00E9} muito velha. Quero trep\u{00E1}-la um dia!",
            ageGroup: .young
        ),
    ]

    private static let middleTextsEN: [ReadingText] = [
        ReadingText(
            id: "m1", titleEN: "The Secret Garden", titleNO: "Den hemmelige hagen",
            titleES: "El jard\u{00ED}n secreto", titlePT: "O jardim secreto",
            contentEN: "Last summer, my family moved to a new house. Behind the house, there was a tall wooden fence covered in green vines. One day, I found a small rusty key under a rock near the gate. I tried the key in the old lock, and it turned! The gate creaked open slowly. Behind it was the most beautiful garden I had ever seen. There were flowers of every color, red roses, purple violets, and bright yellow sunflowers that were taller than me. A small fountain bubbled in the middle, and butterflies danced from flower to flower. I decided this would be my secret place. Every afternoon after school, I would come here to read, draw, and dream. The garden became my favorite spot in the whole world.",
            contentNO: "Forrige sommer flyttet familien min til et nytt hus. Bak huset var det et h\u{00F8}yt tregjerde dekket med gr\u{00F8}nne slyngplanter. En dag fant jeg en liten rusten n\u{00F8}kkel under en stein ved porten. Jeg pr\u{00F8}vde n\u{00F8}kkelen i den gamle l\u{00E5}sen, og den snudde! Porten knirket sakte opp. Bak den var den vakreste hagen jeg noensinne hadde sett. Det var blomster i alle farger, r\u{00F8}de roser, lilla fioler og lyse gule solsikker som var h\u{00F8}yere enn meg. En liten fontene boblet i midten, og sommerfugler danset fra blomst til blomst. Jeg bestemte meg for at dette skulle v\u{00E6}re mitt hemmelige sted. Hver ettermiddag etter skolen kom jeg hit for \u{00E5} lese, tegne og dr\u{00F8}mme. Hagen ble mitt favorittsted i hele verden.",
            contentES: "El verano pasado, mi familia se mud\u{00F3} a una casa nueva. Detr\u{00E1}s de la casa hab\u{00ED}a una valla alta de madera cubierta de enredaderas verdes. Un d\u{00ED}a encontr\u{00E9} una peque\u{00F1}a llave oxidada debajo de una piedra, cerca de la puerta. Prob\u{00E9} la llave en la cerradura antigua y gir\u{00F3}! La puerta se abri\u{00F3} lentamente con un chirrido. Detr\u{00E1}s estaba el jard\u{00ED}n m\u{00E1}s bonito que hab\u{00ED}a visto en mi vida. Hab\u{00ED}a flores de todos los colores: rosas rojas, violetas moradas y girasoles amarillos brillantes m\u{00E1}s altos que yo. En el centro burbujeaba una peque\u{00F1}a fuente y las mariposas bailaban de flor en flor. Decid\u{00ED} que aquel ser\u{00ED}a mi lugar secreto. Cada tarde, despu\u{00E9}s de la escuela, ven\u{00ED}a all\u{00ED} a leer, dibujar y so\u{00F1}ar. El jard\u{00ED}n se convirti\u{00F3} en mi rinc\u{00F3}n favorito del mundo entero.",
            contentPT: "No ver\u{00E3}o passado, a minha fam\u{00ED}lia mudou-se para uma casa nova. Atr\u{00E1}s da casa havia uma cerca alta de madeira coberta de trepadeiras verdes. Um dia encontrei uma pequena chave enferrujada debaixo de uma pedra, perto do port\u{00E3}o. Experimentei a chave na fechadura antiga e ela rodou! O port\u{00E3}o abriu-se devagar com um ranger. Atr\u{00E1}s dele estava o jardim mais bonito que eu alguma vez tinha visto. Havia flores de todas as cores: rosas vermelhas, violetas roxas e girass\u{00F3}is amarelos brilhantes mais altos do que eu. No meio borbulhava uma pequena fonte e as borboletas dan\u{00E7}avam de flor em flor. Decidi que aquele seria o meu lugar secreto. Todas as tardes, depois da escola, vinha aqui para ler, desenhar e sonhar. O jardim tornou-se o meu lugar preferido em todo o mundo.",
            ageGroup: .middle
        ),
        ReadingText(
            id: "m2", titleEN: "The Brave Little Fox", titleNO: "Den modige lille reven",
            titleES: "El peque\u{00F1}o zorro valiente", titlePT: "A pequena raposa valente",
            contentEN: "Deep in the forest, a young fox named Finn lived with his mother. Finn was smaller than the other foxes, but he was very clever. One cold winter morning, Finn woke up to find that a heavy snowstorm had blocked the entrance to their den. His mother was still sleeping. Finn knew he had to find another way out. He dug carefully through the soft snow on the side of the hill. After a long time, he broke through to the outside. The world was white and sparkling. Finn found berries under the snow and brought them home for breakfast. His mother was so proud of him. From that day on, everyone in the forest called him Finn the Brave.",
            contentNO: "Dypt inne i skogen bodde en ung rev som het Finn sammen med moren sin. Finn var mindre enn de andre revene, men han var veldig smart. En kald vintermorgon v\u{00E5}knet Finn og oppdaget at en kraftig sn\u{00F8}storm hadde blokkert inngangen til hiet deres. Moren hans sov fortsatt. Finn visste at han m\u{00E5}tte finne en annen vei ut. Han gravde forsiktig gjennom den myke sn\u{00F8}en p\u{00E5} siden av h\u{00F8}yden. Etter lang tid brøt han gjennom til utsiden. Verden var hvit og glitrende. Finn fant b\u{00E6}r under sn\u{00F8}en og tok dem med hjem til frokost. Moren hans var s\u{00E5} stolt av ham. Fra den dagen kalte alle i skogen ham Finn den Modige.",
            contentES: "En lo profundo del bosque, un joven zorro llamado Finn viv\u{00ED}a con su madre. Finn era m\u{00E1}s peque\u{00F1}o que los otros zorros, pero era muy listo. Una fr\u{00ED}a ma\u{00F1}ana de invierno, Finn se despert\u{00F3} y descubri\u{00F3} que una gran tormenta de nieve hab\u{00ED}a bloqueado la entrada de su madriguera. Su madre segu\u{00ED}a dormida. Finn sab\u{00ED}a que ten\u{00ED}a que encontrar otra salida. Cav\u{00F3} con cuidado a trav\u{00E9}s de la nieve blanda en el lado de la colina. Despu\u{00E9}s de mucho tiempo, logr\u{00F3} salir al exterior. El mundo estaba blanco y brillante. Finn encontr\u{00F3} bayas bajo la nieve y las llev\u{00F3} a casa para desayunar. Su madre se sinti\u{00F3} muy orgullosa de \u{00E9}l. Desde aquel d\u{00ED}a, todos en el bosque lo llamaron Finn el Valiente.",
            contentPT: "No fundo da floresta, uma jovem raposa chamada Finn vivia com a m\u{00E3}e. O Finn era mais pequeno do que as outras raposas, mas era muito esperto. Numa manh\u{00E3} fria de inverno, o Finn acordou e descobriu que uma grande tempestade de neve tinha bloqueado a entrada da toca. A m\u{00E3}e ainda estava a dormir. O Finn sabia que tinha de encontrar outra sa\u{00ED}da. Escavou com cuidado pela neve fofa na encosta do monte. Passado muito tempo, conseguiu abrir caminho at\u{00E9} ao exterior. O mundo estava branco e brilhante. O Finn encontrou bagas debaixo da neve e levou-as para casa para o pequeno-almo\u{00E7}o. A m\u{00E3}e ficou muito orgulhosa dele. A partir desse dia, todos na floresta lhe chamaram Finn, o Valente.",
            ageGroup: .middle
        ),
        ReadingText(
            id: "m3", titleEN: "Amazing Octopuses", titleNO: "Fantastiske blekkspruter",
            titleES: "Pulpos asombrosos", titlePT: "Polvos incr\u{00ED}veis",
            contentEN: "Did you know that octopuses are some of the smartest animals in the ocean? They have eight long arms and a soft body with no bones at all. This means they can squeeze through tiny spaces, even through a hole as small as a coin! Octopuses can also change their color in less than a second. They do this to hide from danger or to talk to other octopuses. Some octopuses even pick up coconut shells and carry them around to use as shelters. Scientists have watched octopuses solve puzzles and open jars to get food inside. They are truly amazing creatures that still surprise us with new discoveries every year.",
            contentNO: "Visste du at blekkspruter er noen av de smarteste dyrene i havet? De har \u{00E5}tte lange armer og en myk kropp uten noen bein i det hele tatt. Det betyr at de kan presse seg gjennom sm\u{00E5} \u{00E5}pninger, til og med gjennom et hull s\u{00E5} lite som en mynt! Blekkspruter kan ogs\u{00E5} endre farge p\u{00E5} under ett sekund. De gj\u{00F8}r dette for \u{00E5} gjemme seg for fare eller for \u{00E5} snakke med andre blekkspruter. Noen blekkspruter plukker til og med opp kokosskall og b\u{00E6}rer dem rundt for \u{00E5} bruke som ly. Forskere har sett blekkspruter l\u{00F8}se puslespill og \u{00E5}pne glass for \u{00E5} f\u{00E5} tak i mat. De er virkelig fantastiske skapninger.",
            contentES: "\u{00BF}Sab\u{00ED}as que los pulpos son algunos de los animales m\u{00E1}s inteligentes del oc\u{00E9}ano? Tienen ocho brazos largos y un cuerpo blando sin huesos. Eso significa que pueden pasar por espacios diminutos, incluso por un agujero tan peque\u{00F1}o como una moneda. Los pulpos tambi\u{00E9}n pueden cambiar de color en menos de un segundo. Lo hacen para esconderse del peligro o para comunicarse con otros pulpos. Algunos pulpos incluso recogen c\u{00E1}scaras de coco y las llevan consigo para usarlas como refugio. Los cient\u{00ED}ficos han visto pulpos resolver puzles y abrir frascos para conseguir la comida de dentro. Son criaturas realmente asombrosas que siguen sorprendi\u{00E9}ndonos con nuevos descubrimientos cada a\u{00F1}o.",
            contentPT: "Sabias que os polvos s\u{00E3}o alguns dos animais mais inteligentes do oceano? T\u{00EA}m oito bra\u{00E7}os compridos e um corpo mole sem ossos. Isto significa que conseguem passar por espa\u{00E7}os muito pequenos, at\u{00E9} por um buraco do tamanho de uma moeda. Os polvos tamb\u{00E9}m conseguem mudar de cor em menos de um segundo. Fazem isso para se esconder do perigo ou para comunicar com outros polvos. Alguns polvos chegam at\u{00E9} a apanhar cascas de coco e a transport\u{00E1}-las para as usar como abrigo. Os cientistas j\u{00E1} observaram polvos a resolver puzzles e a abrir frascos para apanhar a comida l\u{00E1} dentro. S\u{00E3}o criaturas verdadeiramente incr\u{00ED}veis que continuam a surpreender-nos com novas descobertas todos os anos.",
            ageGroup: .middle
        ),
        ReadingText(
            id: "m4", titleEN: "The Lost Kite", titleNO: "Den tapte dragen",
            titleES: "La cometa perdida", titlePT: "O papagaio perdido",
            contentEN: "On a windy Saturday, Emma took her new red kite to the hill near her house. The wind was perfect, and the kite flew high into the sky. Emma laughed as it danced above the clouds. But then a strong gust of wind pulled the string right out of her hands! The kite sailed away over the trees. Emma ran after it as fast as she could. She followed it through the meadow, past the old barn, and all the way to the river. There, caught in a willow tree, was her red kite. A friendly boy named Leo helped her get it down. They spent the rest of the afternoon flying the kite together and became good friends.",
            contentNO: "En vindfull l\u{00F8}rdag tok Emma med seg den nye r\u{00F8}de dragen sin til h\u{00F8}yden n\u{00E6}r huset hennes. Vinden var perfekt, og dragen fl\u{00F8}y h\u{00F8}yt opp p\u{00E5} himmelen. Emma lo mens den danset over skyene. Men s\u{00E5} dro et kraftig vindkast snoren rett ut av hendene hennes! Dragen seilte bort over tr\u{00E6}rne. Emma l\u{00F8}p etter den s\u{00E5} fort hun kunne. Hun fulgte den gjennom engen, forbi den gamle l\u{00E5}ven og helt ned til elven. Der, fanget i et piletre, var den r\u{00F8}de dragen hennes. En hyggelig gutt som het Leo hjalp henne med \u{00E5} f\u{00E5} den ned. De tilbrakte resten av ettermiddagen med \u{00E5} fly dragen sammen og ble gode venner.",
            contentES: "Un s\u{00E1}bado ventoso, Emma llev\u{00F3} su nueva cometa roja a la colina cerca de su casa. El viento era perfecto y la cometa vol\u{00F3} muy alto en el cielo. Emma se re\u{00ED}a mientras bailaba sobre las nubes. Pero entonces una fuerte racha de viento le arranc\u{00F3} la cuerda de las manos! La cometa se alej\u{00F3} por encima de los \u{00E1}rboles. Emma corri\u{00F3} tras ella tan r\u{00E1}pido como pudo. La sigui\u{00F3} por el prado, pas\u{00F3} junto al viejo granero y lleg\u{00F3} hasta el r\u{00ED}o. All\u{00ED}, atrapada en un sauce, estaba su cometa roja. Un ni\u{00F1}o simp\u{00E1}tico llamado Leo le ayud\u{00F3} a bajarla. Pasaron el resto de la tarde volando la cometa juntos y se hicieron muy buenos amigos.",
            contentPT: "Num s\u{00E1}bado ventoso, a Emma levou o seu novo papagaio vermelho para a colina perto de casa. O vento estava perfeito e o papagaio voou bem alto no c\u{00E9}u. A Emma ria-se enquanto ele dan\u{00E7}ava por cima das nuvens. Mas depois uma rajada forte arrancou-lhe a linha das m\u{00E3}os! O papagaio voou por cima das \u{00E1}rvores. A Emma correu atr\u{00E1}s dele o mais depressa que conseguiu. Seguiu-o pelo prado, passou pelo celeiro velho e foi at\u{00E9} ao rio. Ali, preso num salgueiro, estava o seu papagaio vermelho. Um rapaz simp\u{00E1}tico chamado Leo ajudou-a a tir\u{00E1}-lo de l\u{00E1}. Passaram o resto da tarde a empinar o papagaio juntos e tornaram-se bons amigos.",
            ageGroup: .middle
        ),
    ]

    private static let olderTextsEN: [ReadingText] = [
        ReadingText(
            id: "o1", titleEN: "The Mystery of the Lighthouse", titleNO: "Mysteriet p\u{00E5} fyret",
            titleES: "El misterio del faro", titlePT: "O mist\u{00E9}rio do farol",
            contentEN: "The old lighthouse on Gull Island had been abandoned for twenty years. Nobody went there anymore, not since the last keeper had left without a word. But every night, the people in the fishing village across the bay could still see a faint light flickering in the tower window. Some said it was just the moonlight reflecting off the glass. Others whispered that it was the ghost of Captain Morgan, who had disappeared during a terrible storm long ago. Twelve-year-old Maya did not believe in ghosts. She was curious and brave, and she wanted to find out the truth. One foggy morning, she borrowed her uncle\u{2019}s rowboat and paddled across the bay to the island. The lighthouse door was unlocked. Inside, the spiral staircase was dusty but solid. She climbed all the way to the top. There, in the lamp room, she found something unexpected: a family of barn owls had made their nest right next to the old mirror. When the moonlight hit the mirror, it reflected through the glass and created the mysterious glow. Maya smiled. The mystery was solved, and she had made some feathery new friends.",
            contentNO: "Det gamle fyret p\u{00E5} M\u{00E5}ke\u{00F8}ya hadde st\u{00E5}tt forlatt i tjue \u{00E5}r. Ingen dro dit lenger, ikke siden den siste fyrpasseren hadde dratt uten et ord. Men hver natt kunne folkene i fiskerlandsbyen p\u{00E5} den andre siden av bukten fortsatt se et svakt lys som flimret i t\u{00E5}rnvinduet. Noen sa det bare var m\u{00E5}nelyset som reflekterte i glasset. Andre hvisket at det var sp\u{00F8}kelset til Kaptein Morgan, som hadde forsvunnet under en fryktelig storm for lenge siden. Tolv \u{00E5}r gamle Maya trodde ikke p\u{00E5} sp\u{00F8}kelser. Hun var nysgjerrig og modig, og hun ville finne ut sannheten. En t\u{00E5}kete morgen l\u{00E5}nte hun onkelens rob\u{00E5}t og rodde over bukten til \u{00F8}ya. Fyrd\u{00F8}ren var ul\u{00E5}st. Inni var vindeltrappen st\u{00F8}vete, men solid. Hun klatret helt opp til toppen. Der, i lamprommet, fant hun noe uventet: en familie med t\u{00E5}rnugler hadde laget reir rett ved siden av det gamle speilet. N\u{00E5}r m\u{00E5}nelyset traff speilet, reflekterte det gjennom glasset og skapte den mystiske gløden. Maya smilte. Mysteriet var l\u{00F8}st, og hun hadde f\u{00E5}tt noen fjærlete nye venner.",
            contentES: "El viejo faro de la Isla Gaviota llevaba veinte años abandonado. Ya nadie iba allí, desde que el último farero se marchó sin decir una palabra. Pero cada noche, la gente del pueblo pesquero al otro lado de la bahía seguía viendo una luz tenue parpadear en la ventana de la torre. Algunos decían que era solo la luz de la luna reflejada en el cristal. Otros susurraban que era el fantasma del capitán Morgan, que había desaparecido durante una terrible tormenta hacía mucho tiempo. Maya, de doce años, no creía en fantasmas. Era curiosa y valiente, y quería descubrir la verdad. Una mañana de niebla, pidió prestada la barca de remos de su tío y cruzó la bahía hasta la isla. La puerta del faro estaba sin cerrar. Dentro, la escalera de caracol estaba cubierta de polvo, pero era firme. Subió hasta arriba del todo. Allí, en la sala de la lámpara, encontró algo inesperado: una familia de lechuzas había hecho su nido justo al lado del viejo espejo. Cuando la luz de la luna golpeaba el espejo, se reflejaba a través del cristal y creaba aquel brillo misterioso. Maya sonrió. El misterio estaba resuelto, y además había hecho unos nuevos amigos con plumas.",
            contentPT: "O velho farol da Ilha da Gaivota estava abandonado há vinte anos. Já ninguém ia lá, desde que o último faroleiro se tinha ido embora sem dizer uma palavra. Mas, todas as noites, as pessoas da aldeia piscatória do outro lado da baía continuavam a ver uma luz fraca a cintilar na janela da torre. Uns diziam que era apenas o luar refletido no vidro. Outros sussurravam que era o fantasma do Capitão Morgan, que desaparecera durante uma tempestade terrível muitos anos antes. Maya, de doze anos, não acreditava em fantasmas. Era curiosa e corajosa, e queria descobrir a verdade. Numa manhã enevoada, pediu emprestado o barco a remos do tio e atravessou a baía até à ilha. A porta do farol estava destrancada. Lá dentro, a escada em caracol estava cheia de pó, mas era sólida. Subiu até ao topo. Ali, na sala da lâmpada, encontrou algo inesperado: uma família de corujas-das-torres tinha feito ninho mesmo ao lado do espelho antigo. Quando o luar batia no espelho, refletia-se através do vidro e criava aquele brilho misterioso. Maya sorriu. O mistério estava resolvido, e ela tinha feito alguns novos amigos emplumados.",
            ageGroup: .older
        ),
        ReadingText(
            id: "o2", titleEN: "Life on Mars?", titleNO: "Liv p\u{00E5} Mars?",
            titleES: "¿Vida en Marte?", titlePT: "Vida em Marte?",
            contentEN: "For hundreds of years, people have looked up at the red dot in the night sky and wondered: is there life on Mars? Today, scientists are closer than ever to finding out. Mars is the fourth planet from the Sun and the most similar to Earth in our solar system. It has seasons, polar ice caps, and even dust storms that can cover the entire planet. Several robots, called rovers, have been sent to explore the surface of Mars. They have found dried-up riverbeds, which means water once flowed there. Where there is water, there might be life, even if it is just tiny bacteria. Scientists are also planning to send humans to Mars within the next twenty years. The journey would take about seven months. The astronauts would need to bring everything with them: food, water, air, and building materials. Some people dream of one day building cities on Mars. It sounds like science fiction, but many of the technologies we need are already being developed right now. Perhaps one day, you could be among the first people to walk on another planet.",
            contentNO: "I hundrevis av \u{00E5}r har folk sett opp p\u{00E5} den r\u{00F8}de prikken p\u{00E5} nattehimmelen og lurt: finnes det liv p\u{00E5} Mars? I dag er forskere n\u{00E6}rmere enn noensinne \u{00E5} finne ut. Mars er den fjerde planeten fra solen og den mest like Jorden i solsystemet v\u{00E5}rt. Den har \u{00E5}rstider, polare iskapper og til og med sandstormer som kan dekke hele planeten. Flere roboter, kalt rovere, har blitt sendt for \u{00E5} utforske overflaten p\u{00E5} Mars. De har funnet utt\u{00F8}rkede elveleier, noe som betyr at vann en gang fløt der. Der det er vann, kan det v\u{00E6}re liv, selv om det bare er sm\u{00E5} bakterier. Forskere planlegger ogs\u{00E5} \u{00E5} sende mennesker til Mars i l\u{00F8}pet av de neste tjue \u{00E5}rene. Reisen ville ta omtrent syv m\u{00E5}neder. Astronautene m\u{00E5} ta med seg alt: mat, vann, luft og byggematerialer. Noen dr\u{00F8}mmer om \u{00E5} en dag bygge byer p\u{00E5} Mars. Det h\u{00F8}res ut som science fiction, men mange av teknologiene vi trenger, blir allerede utviklet n\u{00E5}. Kanskje en dag kan du v\u{00E6}re blant de f\u{00F8}rste som g\u{00E5}r p\u{00E5} en annen planet.",
            contentES: "Durante cientos de años, la gente ha mirado el punto rojo en el cielo nocturno y se ha preguntado: ¿hay vida en Marte? Hoy, los científicos están más cerca que nunca de averiguarlo. Marte es el cuarto planeta desde el Sol y el más parecido a la Tierra en nuestro sistema solar. Tiene estaciones, casquetes polares e incluso tormentas de polvo que pueden cubrir el planeta entero. Varios robots, llamados rovers, han sido enviados para explorar la superficie de Marte. Han encontrado antiguos cauces de ríos secos, lo que significa que alguna vez hubo agua allí. Donde hay agua, podría haber vida, aunque solo sean bacterias diminutas. Los científicos también planean enviar seres humanos a Marte en los próximos veinte años. El viaje duraría unos siete meses. Los astronautas tendrían que llevar consigo todo: comida, agua, aire y materiales de construcción. Algunas personas sueñan con construir algún día ciudades en Marte. Suena a ciencia ficción, pero muchas de las tecnologías que necesitamos ya se están desarrollando ahora mismo. Quizá algún día podrías estar entre las primeras personas en caminar sobre otro planeta.",
            contentPT: "Durante centenas de anos, as pessoas olharam para o ponto vermelho no céu noturno e perguntaram-se: existirá vida em Marte? Hoje, os cientistas estão mais perto do que nunca de descobrir. Marte é o quarto planeta a contar do Sol e o mais parecido com a Terra no nosso sistema solar. Tem estações, calotes polares e até tempestades de poeira que podem cobrir o planeta inteiro. Vários robôs, chamados rovers, foram enviados para explorar a superfície de Marte. Encontraram leitos de rios secos, o que significa que ali já correu água. Onde há água, pode haver vida, nem que seja apenas bactérias minúsculas. Os cientistas também estão a planear enviar seres humanos para Marte nos próximos vinte anos. A viagem demoraria cerca de sete meses. Os astronautas teriam de levar tudo consigo: comida, água, ar e materiais de construção. Algumas pessoas sonham em construir um dia cidades em Marte. Parece ficção científica, mas muitas das tecnologias de que precisamos já estão a ser desenvolvidas neste momento. Talvez um dia possas estar entre as primeiras pessoas a caminhar noutro planeta.",
            ageGroup: .older
        ),
        ReadingText(
            id: "o3", titleEN: "The Clockmaker\u{2019}s Apprentice", titleNO: "Klokkemakerens l\u{00E6}rling",
            titleES: "El aprendiz de relojero", titlePT: "O aprendiz de relojoeiro",
            contentEN: "In a small town tucked between two mountains, there lived an old clockmaker named Mr. Stein. His shop was filled with hundreds of clocks of every shape and size. Grandfather clocks, cuckoo clocks, pocket watches, and tiny music boxes that played beautiful melodies when you opened them. Every clock in Mr. Stein\u{2019}s shop told perfect time. When ten-year-old Aiden walked past the shop one afternoon, he stopped and pressed his nose against the glass. The window was full of spinning gears, swinging pendulums, and ticking hands. Mr. Stein saw the boy and waved him inside. That was the beginning of an unexpected friendship. Every day after school, Aiden would visit the shop. Mr. Stein taught him how gears work together, how springs store energy, and how a tiny balance wheel keeps time with incredible accuracy. Aiden learned to take apart a clock and put it back together with steady hands and patience. By the end of the year, Aiden had built his very first clock from scratch. It was not perfect, but it kept time, and Mr. Stein said that was the most important thing.",
            contentNO: "I en liten by mellom to fjell bodde det en gammel klokkemaker som het herr Stein. Butikken hans var fylt med hundrevis av klokker i alle former og st\u{00F8}rrelser. Gulvklokker, gj\u{00F8}kklokker, lommeur og sm\u{00E5} spilledoser som spilte vakre melodier n\u{00E5}r du \u{00E5}pnet dem. Hver klokke i herr Steins butikk viste perfekt tid. Da ti \u{00E5}r gamle Aiden gikk forbi butikken en ettermiddag, stoppet han og presset nesen mot glasset. Vinduet var fullt av snurrende tannhjul, svingende pendler og tikkende visere. Herr Stein s\u{00E5} gutten og vinket ham inn. Det var begynnelsen p\u{00E5} et uventet vennskap. Hver dag etter skolen bes\u{00F8}kte Aiden butikken. Herr Stein l\u{00E6}rte ham hvordan tannhjul fungerer sammen, hvordan fj\u{00E6}rer lagrer energi, og hvordan et lite balansehjul holder tiden med utrolig n\u{00F8}yaktighet. Aiden l\u{00E6}rte \u{00E5} ta fra hverandre en klokke og sette den sammen igjen med st\u{00F8}dige hender og t\u{00E5}lmodighet. Ved slutten av \u{00E5}ret hadde Aiden bygget sin aller f\u{00F8}rste klokke fra bunnen av. Den var ikke perfekt, men den holdt tiden, og herr Stein sa at det var det viktigste.",
            contentES: "En un pequeño pueblo escondido entre dos montañas vivía un viejo relojero llamado señor Stein. Su tienda estaba llena de cientos de relojes de todas las formas y tamaños. Relojes de pie, relojes de cuco, relojes de bolsillo y pequeñas cajas de música que tocaban hermosas melodías al abrirlas. Todos los relojes de la tienda del señor Stein daban la hora perfecta. Cuando Aiden, de diez años, pasó por la tienda una tarde, se detuvo y pegó la nariz al cristal. El escaparate estaba lleno de engranajes girando, péndulos balanceándose y agujas haciendo tic-tac. El señor Stein vio al niño y le hizo señas para que entrara. Así comenzó una amistad inesperada. Cada día después de la escuela, Aiden visitaba la tienda. El señor Stein le enseñó cómo trabajan juntos los engranajes, cómo los muelles guardan energía y cómo una pequeña rueda reguladora mantiene el tiempo con una precisión increíble. Aiden aprendió a desmontar un reloj y volver a montarlo con manos firmes y paciencia. Al final del año, Aiden había construido su primer reloj desde cero. No era perfecto, pero daba la hora, y el señor Stein decía que eso era lo más importante.",
            contentPT: "Numa pequena vila escondida entre duas montanhas vivia um velho relojoeiro chamado senhor Stein. A sua loja estava cheia de centenas de relógios de todas as formas e tamanhos. Relógios de pé, cucos, relógios de bolso e pequenas caixas de música que tocavam lindas melodias quando se abriam. Todos os relógios da loja do senhor Stein marcavam a hora certa. Quando o Aiden, de dez anos, passou pela loja numa tarde, parou e encostou o nariz ao vidro. A montra estava cheia de engrenagens a girar, pêndulos a baloiçar e ponteiros a fazer tic-tac. O senhor Stein viu o rapaz e fez-lhe sinal para entrar. Foi assim que começou uma amizade inesperada. Todos os dias, depois da escola, o Aiden visitava a loja. O senhor Stein ensinou-lhe como as engrenagens trabalham juntas, como as molas guardam energia e como uma pequena roda de balanço marca o tempo com uma precisão incrível. O Aiden aprendeu a desmontar um relógio e a montá-lo outra vez com mãos firmes e muita paciência. No fim do ano, o Aiden tinha construído o seu primeiro relógio de raiz. Não era perfeito, mas dava horas, e o senhor Stein dizia que isso era o mais importante.",
            ageGroup: .older
        ),
        ReadingText(
            id: "o4", titleEN: "The Deep Ocean", titleNO: "Det dype havet",
            titleES: "El océano profundo", titlePT: "O oceano profundo",
            contentEN: "The ocean covers more than seventy percent of our planet, yet we have explored less than five percent of it. The deepest point on Earth is the Mariana Trench in the Pacific Ocean. It goes down nearly eleven kilometers, deeper than Mount Everest is tall! At the bottom, the pressure is so great that it would crush most submarines. The water is near freezing and completely dark because sunlight cannot reach that far. Yet even in this extreme environment, life exists. Scientists have discovered strange creatures that glow in the dark, fish with enormous eyes that can see in almost no light, and tiny organisms that survive on chemicals from underwater volcanoes instead of sunlight. Some of these creatures look like they belong in a science fiction movie. Every time a deep-sea expedition goes down, it finds species that have never been seen before. The ocean floor is truly the last frontier on Earth, and exploring it is one of the greatest adventures of our time.",
            contentNO: "Havet dekker mer enn sytti prosent av planeten v\u{00E5}r, men vi har utforsket mindre enn fem prosent av det. Det dypeste punktet p\u{00E5} Jorden er Marianergropen i Stillehavet. Den g\u{00E5}r nesten elleve kilometer ned, dypere enn Mount Everest er h\u{00F8}y! P\u{00E5} bunnen er trykket s\u{00E5} stort at det ville knuse de fleste ub\u{00E5}ter. Vannet er nesten frysende og helt m\u{00F8}rkt fordi sollys ikke n\u{00E5}r s\u{00E5} langt. Likevel finnes det liv selv i dette ekstreme milj\u{00F8}et. Forskere har oppdaget merkelige skapninger som lyser i m\u{00F8}rket, fisker med enorme \u{00F8}yne som kan se i nesten ikke noe lys, og sm\u{00E5} organismer som overlever p\u{00E5} kjemikalier fra undervannsvulkaner i stedet for sollys. Noen av disse skapningene ser ut som de h\u{00F8}rer hjemme i en science fiction-film. Hver gang en dyphavsekspedisjon g\u{00E5}r ned, finner den arter som aldri har blitt sett f\u{00F8}r. Havbunnen er virkelig den siste grensen p\u{00E5} Jorden.",
            contentES: "El océano cubre más del setenta por ciento de nuestro planeta, y aun así hemos explorado menos del cinco por ciento. El punto más profundo de la Tierra es la fosa de las Marianas, en el océano Pacífico. Desciende casi once kilómetros, más de lo que mide el monte Everest. En el fondo, la presión es tan grande que aplastaría a la mayoría de los submarinos. El agua está casi helada y totalmente oscura porque la luz del sol no llega tan lejos. Y aun así, incluso en este entorno extremo, existe vida. Los científicos han descubierto criaturas extrañas que brillan en la oscuridad, peces con ojos enormes capaces de ver con casi nada de luz y pequeños organismos que sobreviven gracias a los químicos de volcanes submarinos en lugar de la luz solar. Algunas de estas criaturas parecen sacadas de una película de ciencia ficción. Cada vez que una expedición al fondo del mar desciende, encuentra especies que nunca se habían visto antes. El suelo oceánico es realmente la última frontera de la Tierra, y explorarlo es una de las grandes aventuras de nuestro tiempo.",
            contentPT: "O oceano cobre mais de setenta por cento do nosso planeta, e mesmo assim explorámos menos de cinco por cento dele. O ponto mais profundo da Terra é a Fossa das Marianas, no oceano Pacífico. Desce quase onze quilómetros, mais fundo do que a altura do monte Evereste. No fundo, a pressão é tão grande que esmagaria a maioria dos submarinos. A água está perto de congelar e é completamente escura porque a luz do sol não chega tão longe. Mesmo assim, até neste ambiente extremo existe vida. Os cientistas descobriram criaturas estranhas que brilham no escuro, peixes com olhos enormes que conseguem ver com quase nenhuma luz e pequenos organismos que sobrevivem com substâncias químicas de vulcões submarinos em vez da luz solar. Algumas destas criaturas parecem saídas de um filme de ficção científica. Cada vez que uma expedição ao fundo do mar desce, encontra espécies nunca vistas antes. O fundo do oceano é verdadeiramente a última fronteira da Terra, e explorá-lo é uma das maiores aventuras do nosso tempo.",
            ageGroup: .older
        ),
    ]
}
